### PR TITLE
Use different fonts and update with upstream

### PR DESCRIPTION
**Pull request by kgrz**
Most UI changes are done on the user facing side, with some changes on the admin facing pages. Adding some screenshots.

cfpapp
cfpapp 2
cfpapp 3

### CODE REVIEW

**Comment by kgrz** [comment]
Pretty hard to review this commit, I'm sure. Most of the changes I made are on the html part. Didn't have to touch the backend code IIRC.

**Comment by swanandp** [comment]
Looks like some of the upstream changes are pulled in.  Can you update
gcrc/cfp with upstream please ?

**Comment by kgrz** [comment]
> Looks like some of the upstream changes are pulled in.  Can you update
> gcrc/cfp with upstream please ?

This is to sync both upstream and make the changes I made. The commits
that were made by you on the GCRC fork, the ruby-central updates and the
ones I made are now on this PR. I'm not opening multiple ones to save
time.

I made most of the changes after getting all the updates from
ruby-central fork.

**Comment by kgrz** [comment]
Swanand gave :+1: on Slack. merging this.

**Pull request merged**
